=== hsej/xml/files/table.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.sa.dk/xmlns/siard/1.0/schema0/table.xsd"
           elementFormDefault="qualified"
           targetNamespace="http://www.sa.dk/xmlns/siard/1.0/schema0/table.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="row" type="rowType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="rowType">
        <xs:sequence>
            <xs:element name="c1" type="xs:integer"/>
            <xs:element name="c2" type="xs:integer"/>
            <xs:element name="c3" type="xs:dateTime"/>
            <xs:element name="c4" nillable="true" type="xs:string"/>
            <xs:element name="c5" nillable="true" type="xs:string"/>
            <xs:element name="c6" nillable="true" type="xs:string"/>
            <xs:element name="c7" nillable="true" type="xs:string"/>
            <xs:element name="c8" type="xs:integer"/>
            <xs:element name="c9" type="xs:string"/>
            <xs:element name="c10" type="xs:string"/>
            <xs:element name="c11" type="xs:string"/>
            <xs:element name="c12" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== hsej/xml/files/table.xml
<?xml version="1.0" encoding="UTF-8"?>
<table xmlns="http://www.sa.dk/xmlns/siard/1.0/schema0/table.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.sa.dk/xmlns/siard/1.0/schema0/table.xsd table.xsd">
    <row>
        <c1>1</c1>
        <c2>2</c2>
        <c3>1991-09-23T12:00:00.510000</c3>
        <c4 xsi:nil="true"/>
        <c5 xsi:nil="true"/>
        <c6 xsi:nil="true"/>
        <c7 xsi:nil="true"/>
        <c8>3</c8>
        <c9>A</c9>
        <c10>B</c10>
        <c11>C</c11>
        <c12>D</c12>
    </row>
    <row>
        <c1>4</c1>
        <c2>5</c2>
        <c3>1992-10-24T13:00:00.520000</c3>
        <c4 xsi:nil="true"/>
        <c5 xsi:nil="true"/>
        <c6 xsi:nil="true"/>
        <c7 xsi:nil="true"/>
        <c8>6</c8>
        <c9>E</c9>
        <c10>F</c10>
        <c11>G</c11>
        <c12>H</c12>
    </row>
    <row>
        <c1>7</c1>
        <c2>8</c2>
        <c3>1993-11-25T14:00:00.530000</c3>
        <c4 xsi:nil="true"/>
        <c5 xsi:nil="true"/>
        <c6 xsi:nil="true"/>
        <c7 xsi:nil="true"/>
        <c8>9</c8>
        <c9>I</c9>
        <c10>J</c10>
        <c11>K</c11>
        <c12>L</c12>
    </row>
</table>
